# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mart/v1/product.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'mart/v1/product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15mart/v1/product.proto\x12\x07mart.v1\"@\n\x07Product\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bprice_cents\x18\x03 \x01(\x03\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"7\n\x12GetProductResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.mart.v1.Product2W\n\x0eProductService\x12\x45\n\nGetProduct\x12\x1a.mart.v1.GetProductRequest\x1a\x1b.mart.v1.GetProductResponseB Z\x1emart/api/gen/go/mart/v1;martv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mart.v1.product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036mart/api/gen/go/mart/v1;martv1'
  _globals['_PRODUCT']._serialized_start=34
  _globals['_PRODUCT']._serialized_end=98
  _globals['_GETPRODUCTREQUEST']._serialized_start=100
  _globals['_GETPRODUCTREQUEST']._serialized_end=139
  _globals['_GETPRODUCTRESPONSE']._serialized_start=141
  _globals['_GETPRODUCTRESPONSE']._serialized_end=196
  _globals['_PRODUCTSERVICE']._serialized_start=198
  _globals['_PRODUCTSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
