apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-chart.fullname" . }}
  labels:
    {{- include "demo-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "demo-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "demo-chart.fullname" . }}-config
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet: {path: {{ .Values.probes.livenessPath }}, port: http}
          readinessProbe:
            httpGet: {path: {{ .Values.probes.readinessPath }}, port: http}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
